// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT_RwwJaP0fNkVbqAWT08Dcr5135qPNBA',
    appId: '1:846859016038:web:d8a34daa1c52e052ca5aa7',
    messagingSenderId: '846859016038',
    projectId: 'high-school-a6af7',
    authDomain: 'high-school-a6af7.firebaseapp.com',
    storageBucket: 'high-school-a6af7.firebasestorage.app',
    measurementId: 'G-7RT86VNCXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC20wM777Bk6kS_P2OrN81WNvFSifn3B_Q',
    appId: '1:846859016038:android:69e2a8cb059abc01ca5aa7',
    messagingSenderId: '846859016038',
    projectId: 'high-school-a6af7',
    storageBucket: 'high-school-a6af7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADMIHJvkuI-9t3WDIVYG22uVf0eYqOJIs',
    appId: '1:846859016038:ios:df77b4104d081929ca5aa7',
    messagingSenderId: '846859016038',
    projectId: 'high-school-a6af7',
    storageBucket: 'high-school-a6af7.firebasestorage.app',
    iosBundleId: 'com.example.subornoJoyonti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADMIHJvkuI-9t3WDIVYG22uVf0eYqOJIs',
    appId: '1:846859016038:ios:df77b4104d081929ca5aa7',
    messagingSenderId: '846859016038',
    projectId: 'high-school-a6af7',
    storageBucket: 'high-school-a6af7.firebasestorage.app',
    iosBundleId: 'com.example.subornoJoyonti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT_RwwJaP0fNkVbqAWT08Dcr5135qPNBA',
    appId: '1:846859016038:web:aede08cba5a3ab80ca5aa7',
    messagingSenderId: '846859016038',
    projectId: 'high-school-a6af7',
    authDomain: 'high-school-a6af7.firebaseapp.com',
    storageBucket: 'high-school-a6af7.firebasestorage.app',
    measurementId: 'G-NP2PSP81YE',
  );

}